const ProductList = [
    {
        id: 'rec1JZlfCIBOPdcT2',
        title: 'Apple iPhone 15 (128 GB)',
        price: '799.99',
        img: 'https://m.media-amazon.com/images/I/71d7rfSl0wL._SX679_.jpg',
        amount: 0,
    },
    {
        id: 'recB6qcHPxb62YJ75',
        title: 'google pixel',
        price: '499.99',
        img: 'https://m.media-amazon.com/images/I/41Yi91m4tqL._SX300_SY300_QL70_FMwebp_.jpg',
        amount: 0,
    },
    {
        id: 'recdRxBsE14Rr2VuJ',
        title: 'Xiaomi Redmi Note 2',
        price: '699.99',
        img: 'https://m.media-amazon.com/images/I/71aiqeP-APL._SX679_.jpg',
        amount: 0,
    },
    {
        id: 'recwTo160XST3PIeee',
        title: 'Apple iPad Pro 11″ (M4)',
        price: '999.00',
        img: 'https://m.media-amazon.com/images/I/61G6WfvA9vL._SX679_.jpg',
        amount: 0,
    },
    {
        id: 'recwTo160XST3PIoW',
        title: 'Samsung Galaxy S7',
        price: '599.99 ',
        img: 'https://m.media-amazon.com/images/I/51JaSbauK3L._SX300_SY300_QL70_FMwebp_.jpg',
        amount: 0,
    },
    {
        id: 'recwTo160XST3PIo',
        title: 'MacBook Air',
        price: '999.99 ',
        img: 'https://m.media-amazon.com/images/I/719C6bJv8jL._SX679_.jpg',
        amount: 0,
    },
    {
        id: 'recwTo160XST3PIoy',
        title: 'MacBook Pro',
        price: '1860.99 ',
        img: 'https://m.media-amazon.com/images/I/314kVw1vC6L._SY445_SX342_QL70_FMwebp_.jpg',
        amount: 0,
    },
    {
        id: 'recwTo160XST3PIoo',
        title: 'Bose Quietcomfort 45',
        price: '160.00 ',
        img: 'https://m.media-amazon.com/images/I/51Ltm3tbH2L._SX679_.jpg',
        amount: 0,
    },
    {
        id: 'recTo160XST3PIoo',
        title: 'Oneplus Nord CE 3 5G',
        price: '180.99',
        img: 'https://m.media-amazon.com/images/I/61abLrCfF7L._SX679_.jpg',
        amount: 0,
    },
    {
        id: 'recTo160ST3PIoo',
        title: 'Voltas 1.5 ton 3 Star',
        price: '400.99',
        img: 'https://m.media-amazon.com/images/I/51YQcpqaqFL._SX679_.jpg',
        amount: 0,
    },
    {
        id: 'recTo160STIoo',
        title: 'Atomic Habits ',
        price: '49.99',
        img: 'https://m.media-amazon.com/images/I/61Bhf8CdaML._SL1200_.jpg',
        amount: 0,
    },
    {
        id: 'recTo160SToo',
        title: 'Sapiens',
        price: '39.99',
        img: 'https://m.media-amazon.com/images/I/71saezoeckL._SX679_.jpg',
        amount: 0,
    },
    {
        id: 'recTo160Soo',
        title: 'Manifest',
        price: '4.99',
        img: 'https://m.media-amazon.com/images/I/71q2efW4jHL._SY522_.jpg',
        amount: 0,
    },
    {
        id: 'recTo160vvSoo',
        title: 'The Alchemist',
        price: '3.99',
        img: 'https://m.media-amazon.com/images/I/61HAE8zahLL._SY522_.jpg',
        amount: 0,
    },
];
export default ProductList;